In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
cd /content/drive/MyDrive/Github/DataScience2023

/content/drive/MyDrive/Github/DataScience2023

In [3]:
!git config --global user.email 'ahnyh4756@gmail.com'
!git config --global user.name 'JejuSudal'

!git remote remove origin
!git remote add origin https://AnYeHyeon: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@github.com/AnYeHyeon/DataScience2023.git

In [8]:
!git add -A
!git commit -m "Connect Google Colab and Drive"
!git push -u origin main

[main 34d800b] Connect Google Colab and Drive
 2 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 "1_2_\341\204\203\341\205\246\341\204\213\341\205\265\341\204\220\341\205\245\341\204\207\341\205\247\341\206\253\341\204\222\341\205\252\341\206\253.ipynb"
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.75 KiB | 447.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/AnYeHyeon/DataScience2023.git
   448bdc1..34d800b  main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

In [5]:
import pandas as pd

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/heart.csv')
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

## feature 별 기본 통계량

In [11]:
df.describe() # 남자가 1, 여자가 0: 남자가 더 많네

,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [12]:
df.isnull()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [13]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [15]:
df = df.dropna(axis=0)

# 데이터의 종류
- numeric (실수형 값)
- categorical (범수형 값)
    - one-hot encodding
    - pd.get_dummies()

In [16]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [21]:
c = ['Sex', 'ChestPain', 'Thal', 'AHD']

In [22]:
df2 = pd.get_dummies(df, columns=c)
df2

,Age,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,...,Sex_1,ChestPain_asymptomatic,ChestPain_nonanginal,ChestPain_nontypical,ChestPain_typical,Thal_fixed,Thal_normal,Thal_reversable,AHD_No,AHD_Yes
0,63,145,233,1,2,150,0,2.3,3,0.0,...,1,0,0,0,1,1,0,0,1,0
1,67,160,286,0,2,108,1,1.5,2,3.0,...,1,1,0,0,0,0,1,0,0,1
2,67,120,229,0,2,129,1,2.6,2,2.0,...,1,1,0,0,0,0,0,1,0,1
3,37,130,250,0,0,187,0,3.5,3,0.0,...,1,0,1,0,0,0,1,0,1,0
4,41,130,204,0,2,172,0,1.4,1,0.0,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,140,241,0,0,123,1,0.2,2,0.0,...,0,1,0,0,0,0,0,1,0,1
298,45,110,264,0,0,132,0,1.2,2,0.0,...,1,0,0,0,1,0,0,1,0,1
299,68,144,193,1,0,141,0,3.4,2,2.0,...,1,1,0,0,0,0,0,1,0,1
300,57,130,131,0,0,115,1,1.2,2,1.0,...,1,1,0,0,0,0,0,1,0,1
301,57,130,236,0,2,174,0,0.0,2,1.0,...,0,0,0,1,0,0,1,0,0,1

In [23]:
df2.columns

Index(['Age', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR', 'ExAng', 'Oldpeak',
       'Slope', 'Ca', 'Sex_0', 'Sex_1', 'ChestPain_asymptomatic',
       'ChestPain_nonanginal', 'ChestPain_nontypical', 'ChestPain_typical',
       'Thal_fixed', 'Thal_normal', 'Thal_reversable', 'AHD_No', 'AHD_Yes'],
      dtype='object')

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/auto.csv')