In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [24]:
cd /content/drive/MyDrive/Github

/content/drive/MyDrive/Github

In [49]:
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Github/DataScience2023/.git/

In [ ]:
!git remote remove

In [47]:
!git remote add origin https://github.com/AnYeHyeon/DataScience2023.git

fatal: remote origin already exists.

In [48]:
!git remote -v

origin	https://github.com/AnYeHyeon/DataScience2023 (fetch)
origin	https://github.com/AnYeHyeon/DataScience2023 (push)

In [12]:
!git clone https://AnYeHyeon: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@github.com/AnYeHyeon/DataScience2023.git

Cloning into 'DataScience2023'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 127 (delta 72), reused 119 (delta 64), pack-reused 0
Receiving objects: 100% (127/127), 106.07 KiB | 4.42 MiB/s, done.
Resolving deltas: 100% (72/72), done.

In [39]:
cd /content/drive/MyDrive/Github/DataScience2023

/content/drive/MyDrive/Github/DataScience2023

In [40]:
!git config --global user.email 'ahnyh4756@gmail.com'
!git config --global user.name 'AnYeHyeon'

In [41]:
!git status

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   "1_2_\341\204\203\341\205\246\341\204\213\341\205\265\341\204\220\341\205\245\341\204\207\341\205\247\341\206\253\341\204\222\341\205\252\341\206\253.ipynb"

no changes added to commit (use "git add" and/or "git commit -a")

In [42]:
!git add -A

In [43]:
!git commit -m "Connect Google Colab and Drive"

[main b235416] Connect Google Colab and Drive
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite "1_2_\341\204\203\341\205\246\341\204\213\341\205\265\341\204\220\341\205\245\341\204\207\341\205\247\341\206\253\341\204\222\341\205\252\341\206\253.ipynb" (84%)

In [44]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/heart.csv')
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

## feature 별 기본 통계량

In [ ]:
df.describe() # 남자가 1, 여자가 0: 남자가 더 많네

,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [ ]:
df.isnull()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [ ]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [ ]:
df = df.dropna(axis=0)

# 데이터의 종류
- numeric (실수형 값)
- categorical (범수형 값)
    - one-hot encodding
    - pd.get_dummies()

In [ ]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [ ]:
c = ['Sex', 'ChestPain', 'Thal', 'AHD']

In [ ]:
df2 = pd.get_dummies(df, columns=c)
df2

,Age,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,...,Sex_1,ChestPain_asymptomatic,ChestPain_nonanginal,ChestPain_nontypical,ChestPain_typical,Thal_fixed,Thal_normal,Thal_reversable,AHD_No,AHD_Yes
0,63,145,233,1,2,150,0,2.3,3,0.0,...,1,0,0,0,1,1,0,0,1,0
1,67,160,286,0,2,108,1,1.5,2,3.0,...,1,1,0,0,0,0,1,0,0,1
2,67,120,229,0,2,129,1,2.6,2,2.0,...,1,1,0,0,0,0,0,1,0,1
3,37,130,250,0,0,187,0,3.5,3,0.0,...,1,0,1,0,0,0,1,0,1,0
4,41,130,204,0,2,172,0,1.4,1,0.0,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,140,241,0,0,123,1,0.2,2,0.0,...,0,1,0,0,0,0,0,1,0,1
298,45,110,264,0,0,132,0,1.2,2,0.0,...,1,0,0,0,1,0,0,1,0,1
299,68,144,193,1,0,141,0,3.4,2,2.0,...,1,1,0,0,0,0,0,1,0,1
300,57,130,131,0,0,115,1,1.2,2,1.0,...,1,1,0,0,0,0,0,1,0,1
301,57,130,236,0,2,174,0,0.0,2,1.0,...,0,0,0,1,0,0,1,0,0,1

In [ ]:
df2.columns

Index(['Age', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR', 'ExAng', 'Oldpeak',
       'Slope', 'Ca', 'Sex_0', 'Sex_1', 'ChestPain_asymptomatic',
       'ChestPain_nonanginal', 'ChestPain_nontypical', 'ChestPain_typical',
       'Thal_fixed', 'Thal_normal', 'Thal_reversable', 'AHD_No', 'AHD_Yes'],
      dtype='object')

# 변수의 표준화
- 표준화 하기전
    - 변수간에 서로 다른 Scale, unit
- 특히 거리 기반의 머신러닝 방법
    - standardize (표준화): 변수가 평균이 0, 표준편차가 1이 되도록 변환
    - min-max scaling: 변수 내에서 가장 큰 값1, 작은값 0

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

## Standardize

In [ ]:
# 공식: (data - mean) / (std)
df.mean()

cylinders          5.471939
displacement     194.411990
horsepower       104.469388
weight          2977.584184
acceleration      15.541327
model_year        75.979592
origin             1.576531
mpg               23.445918
dtype: float64

In [ ]:
df - df.mean()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,2.528061,112.58801,25.530612,526.415816,-3.541327,-5.979592,-0.576531,-5.445918
1,2.528061,155.58801,60.530612,715.415816,-4.041327,-5.979592,-0.576531,-8.445918
2,2.528061,123.58801,45.530612,458.415816,-4.541327,-5.979592,-0.576531,-5.445918
3,2.528061,109.58801,45.530612,455.415816,-3.541327,-5.979592,-0.576531,-7.445918
4,2.528061,107.58801,35.530612,471.415816,-5.041327,-5.979592,-0.576531,-6.445918
...,...,...,...,...,...,...,...,...
387,-1.471939,-54.41199,-18.469388,-187.584184,0.058673,6.020408,-0.576531,3.554082
388,-1.471939,-97.41199,-52.469388,-847.584184,9.058673,6.020408,0.423469,20.554082
389,-1.471939,-59.41199,-20.469388,-682.584184,-3.941327,6.020408,-0.576531,8.554082
390,-1.471939,-74.41199,-25.469388,-352.584184,3.058673,6.020408,-0.576531,4.554082
391,-1.471939,-75.41199,-22.469388,-257.584184,3.858673,6.020408,-0.576531,7.554082

In [ ]:
df.std()

cylinders         1.705783
displacement    104.644004
horsepower       38.491160
weight          849.402560
acceleration      2.758864
model_year        3.683737
origin            0.805518
mpg               7.805007
dtype: float64

In [ ]:
(df-df.mean())/df.std()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.482053,1.075915,0.663285,0.619748,-1.283618,-1.623241,-0.715726,-0.697747
1,1.482053,1.486832,1.572585,0.842258,-1.464852,-1.623241,-0.715726,-1.082115
2,1.482053,1.181033,1.182885,0.539692,-1.646086,-1.623241,-0.715726,-0.697747
3,1.482053,1.047246,1.182885,0.536160,-1.283618,-1.623241,-0.715726,-0.953992
4,1.482053,1.028134,0.923085,0.554997,-1.827320,-1.623241,-0.715726,-0.825870
...,...,...,...,...,...,...,...,...
387,-0.862911,-0.519972,-0.479835,-0.220842,0.021267,1.634321,-0.715726,0.455359
388,-0.862911,-0.930889,-1.363154,-0.997859,3.283479,1.634321,0.525711,2.633448
389,-0.862911,-0.567753,-0.531795,-0.803605,-1.428605,1.634321,-0.715726,1.095974
390,-0.862911,-0.711097,-0.661694,-0.415097,1.108671,1.634321,-0.715726,0.583482
391,-0.862911,-0.720653,-0.583754,-0.303253,1.398646,1.634321,-0.715726,0.967851

## Min-max scaling

In [ ]:
df.max()

cylinders          8.0
displacement     455.0
horsepower       230.0
weight          5140.0
acceleration      24.8
model_year        82.0
origin             3.0
mpg               46.6
dtype: float64

In [ ]:
df.min()

cylinders          3.0
displacement      68.0
horsepower        46.0
weight          1613.0
acceleration       8.0
model_year        70.0
origin             1.0
mpg                9.0
dtype: float64

In [ ]:
(df-df.min())/(df.max()-df.min())

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.0,0.617571,0.456522,0.536150,0.238095,0.0,0.0,0.239362
1,1.0,0.728682,0.646739,0.589736,0.208333,0.0,0.0,0.159574
2,1.0,0.645995,0.565217,0.516870,0.178571,0.0,0.0,0.239362
3,1.0,0.609819,0.565217,0.516019,0.238095,0.0,0.0,0.186170
4,1.0,0.604651,0.510870,0.520556,0.148810,0.0,0.0,0.212766
...,...,...,...,...,...,...,...,...
387,0.2,0.186047,0.217391,0.333711,0.452381,1.0,0.0,0.478723
388,0.2,0.074935,0.032609,0.146583,0.988095,1.0,0.5,0.930851
389,0.2,0.173127,0.206522,0.193365,0.214286,1.0,0.0,0.611702
390,0.2,0.134367,0.179348,0.286929,0.630952,1.0,0.0,0.505319
391,0.2,0.131783,0.195652,0.313864,0.678571,1.0,0.0,0.585106

## sklearn
- 파이썬에서 표준화된 머신러닝 라이브러리
- sklearn에서 제공하는 데이터 표준화 모듈을 사용
- skearn.preprocessing
- MinMaxScaler

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

In [ ]:
# 객체생성
scaler = StandardScaler()
output = scaler.fit_transform(df) #numpy array 형태로 변환시켜서 생성
output

array([[ 1.48394702,  1.07728956,  0.66413273, ..., -1.62531533,
        -0.71664105, -0.69863841],
       [ 1.48394702,  1.48873169,  1.57459447, ..., -1.62531533,
        -0.71664105, -1.08349824],
       [ 1.48394702,  1.1825422 ,  1.18439658, ..., -1.62531533,
        -0.71664105, -0.69863841],
       ...,
       [-0.86401356, -0.56847897, -0.53247413, ...,  1.63640964,
        -0.71664105,  1.09737414],
       [-0.86401356, -0.7120053 , -0.66254009, ...,  1.63640964,
        -0.71664105,  0.5842277 ],
       [-0.86401356, -0.72157372, -0.58450051, ...,  1.63640964,
        -0.71664105,  0.96908753]])

In [ ]:
pd.DataFrame(output, columns = df.columns)

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.483947,1.077290,0.664133,0.620540,-1.285258,-1.625315,-0.716641,-0.698638
1,1.483947,1.488732,1.574594,0.843334,-1.466724,-1.625315,-0.716641,-1.083498
2,1.483947,1.182542,1.184397,0.540382,-1.648189,-1.625315,-0.716641,-0.698638
3,1.483947,1.048584,1.184397,0.536845,-1.285258,-1.625315,-0.716641,-0.955212
4,1.483947,1.029447,0.924265,0.555706,-1.829655,-1.625315,-0.716641,-0.826925
...,...,...,...,...,...,...,...,...
387,-0.864014,-0.520637,-0.480448,-0.221125,0.021294,1.636410,-0.716641,0.455941
388,-0.864014,-0.932079,-1.364896,-0.999134,3.287676,1.636410,0.526382,2.636813
389,-0.864014,-0.568479,-0.532474,-0.804632,-1.430430,1.636410,-0.716641,1.097374
390,-0.864014,-0.712005,-0.662540,-0.415627,1.110088,1.636410,-0.716641,0.584228
391,-0.864014,-0.721574,-0.584501,-0.303641,1.400433,1.636410,-0.716641,0.969088

In [ ]:
scaler = MinMaxScaler()
output = scaler.fit_transform(df)
pd.DataFrame(output, columns = df.columns)

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.0,0.617571,0.456522,0.536150,0.238095,0.0,0.0,0.239362
1,1.0,0.728682,0.646739,0.589736,0.208333,0.0,0.0,0.159574
2,1.0,0.645995,0.565217,0.516870,0.178571,0.0,0.0,0.239362
3,1.0,0.609819,0.565217,0.516019,0.238095,0.0,0.0,0.186170
4,1.0,0.604651,0.510870,0.520556,0.148810,0.0,0.0,0.212766
...,...,...,...,...,...,...,...,...
387,0.2,0.186047,0.217391,0.333711,0.452381,1.0,0.0,0.478723
388,0.2,0.074935,0.032609,0.146583,0.988095,1.0,0.5,0.930851
389,0.2,0.173127,0.206522,0.193365,0.214286,1.0,0.0,0.611702
390,0.2,0.134367,0.179348,0.286929,0.630952,1.0,0.0,0.505319
391,0.2,0.131783,0.195652,0.313864,0.678571,1.0,0.0,0.585106

# Polynormial Term 추가하기
- 선형회귀 모형의 한계를 깨기 위한 방법
- 비선형적인 관계를 표현하는 방법
    - (회귀) 다차항 넣기
    - (분류) 변수간의 상호작용
- sklean에서 제공하는 함수로 손쉽게 해결 가능

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/classification_data.csv")
df

          X1        X2  y
0  -2.056844 -0.752741  0
1   1.760238  1.558517  1
2  -0.447763 -1.554927  1
3   1.008459  0.529517  1
4   0.636547  0.409058  1
..       ...       ... ..
95 -0.129932 -0.797169  0
96  1.426902  1.244639  1
97 -0.582968  1.630750  1
98 -0.619720  1.630840  0
99  1.938929  0.069963  1

[100 rows x 3 columns]

In [5]:
# 독립변수 추리기
x = df[['X1', 'X2']]
x

          X1        X2
0  -2.056844 -0.752741
1   1.760238  1.558517
2  -0.447763 -1.554927
3   1.008459  0.529517
4   0.636547  0.409058
..       ...       ...
95 -0.129932 -0.797169
96  1.426902  1.244639
97 -0.582968  1.630750
98 -0.619720  1.630840
99  1.938929  0.069963

[100 rows x 2 columns]

In [42]:
from sklearn import preprocessing

from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(3, include_bias=False, interaction_only=False) # 몇차식, 상수항(편향), 상호작용 
output = poly.fit_transform(x)

In [43]:
c = poly.get_feature_names_out(x.columns)

In [44]:
pd.DataFrame(output, columns = c)

,X1,X2,X1^2,X1 X2,X2^2,X1^3,X1^2 X2,X1 X2^2,X2^3
0,-2.056844,-0.752741,4.230608,1.548270,0.566618,-8.701702,-3.184551,-1.165446,-0.426517
1,1.760238,1.558517,3.098437,2.743361,2.428977,5.453985,4.828968,4.275576,3.785603
2,-0.447763,-1.554927,0.200492,0.696238,2.417797,-0.089773,-0.311750,-1.082600,-3.759497
3,1.008459,0.529517,1.016990,0.533996,0.280388,1.025592,0.538513,0.282760,0.148470
4,0.636547,0.409058,0.405191,0.260384,0.167328,0.257923,0.165747,0.106512,0.068447
...,...,...,...,...,...,...,...,...,...
95,-0.129932,-0.797169,0.016882,0.103577,0.635478,-0.002194,-0.013458,-0.082569,-0.506584
96,1.426902,1.244639,2.036050,1.775978,1.549126,2.905245,2.534148,2.210452,1.928103
97,-0.582968,1.630750,0.339852,-0.950675,2.659346,-0.198123,0.554213,-1.550313,4.336728
98,-0.619720,1.630840,0.384052,-1.010664,2.659641,-0.238005,0.626328,-1.648231,4.337449
99,1.938929,0.069963,3.759444,0.135652,0.004895,7.289295,0.263020,0.009491,0.000342