In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
cd /content/drive/MyDrive/Github/DataScience2023

/content/drive/MyDrive/Github/DataScience2023

In [3]:
!git config --global user.email 'ahnyh4756@gmail.com'
!git config --global user.name 'AnYeHyeon'

!git remote remove origin
!git remote add origin https://AnYeHyeon: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@github.com/AnYeHyeon/DataScience2023.git

In [31]:
!git add 1_2_데이터변환.ipynb
!git commit -m "Connect Google Colab and Drive"
!git push -u origin main

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    1_2_DataTransforming.ipynb
	modified:   "1_2_\341\204\203\341\205\246\341\204\213\341\205\265\341\204\220\341\205\245\341\204\207\341\205\247\341\206\253\341\204\222\341\205\252\341\206\253.ipynb"
	deleted:    datatransper.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	DataScience2023/

no changes added to commit (use "git add" and/or "git commit -a")
Branch 'main' set up to track remote branch 'main' from 'origin'.
Everything up-to-date

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/heart.csv')
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

## feature 별 기본 통계량

In [7]:
df.describe() # 남자가 1, 여자가 0: 남자가 더 많네

,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [8]:
df.isnull()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [9]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [10]:
df = df.dropna(axis=0)

# 데이터의 종류
- numeric (실수형 값)
- categorical (범수형 값)
    - one-hot encodding
    - pd.get_dummies()

In [11]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [12]:
c = ['Sex', 'ChestPain', 'Thal', 'AHD']

In [13]:
df2 = pd.get_dummies(df, columns=c)
df2

,Age,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,...,Sex_1,ChestPain_asymptomatic,ChestPain_nonanginal,ChestPain_nontypical,ChestPain_typical,Thal_fixed,Thal_normal,Thal_reversable,AHD_No,AHD_Yes
0,63,145,233,1,2,150,0,2.3,3,0.0,...,1,0,0,0,1,1,0,0,1,0
1,67,160,286,0,2,108,1,1.5,2,3.0,...,1,1,0,0,0,0,1,0,0,1
2,67,120,229,0,2,129,1,2.6,2,2.0,...,1,1,0,0,0,0,0,1,0,1
3,37,130,250,0,0,187,0,3.5,3,0.0,...,1,0,1,0,0,0,1,0,1,0
4,41,130,204,0,2,172,0,1.4,1,0.0,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,140,241,0,0,123,1,0.2,2,0.0,...,0,1,0,0,0,0,0,1,0,1
298,45,110,264,0,0,132,0,1.2,2,0.0,...,1,0,0,0,1,0,0,1,0,1
299,68,144,193,1,0,141,0,3.4,2,2.0,...,1,1,0,0,0,0,0,1,0,1
300,57,130,131,0,0,115,1,1.2,2,1.0,...,1,1,0,0,0,0,0,1,0,1
301,57,130,236,0,2,174,0,0.0,2,1.0,...,0,0,0,1,0,0,1,0,0,1

In [14]:
df2.columns

Index(['Age', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR', 'ExAng', 'Oldpeak',
       'Slope', 'Ca', 'Sex_0', 'Sex_1', 'ChestPain_asymptomatic',
       'ChestPain_nonanginal', 'ChestPain_nontypical', 'ChestPain_typical',
       'Thal_fixed', 'Thal_normal', 'Thal_reversable', 'AHD_No', 'AHD_Yes'],
      dtype='object')

# 변수의 표준화
- 표준화 하기전
    - 변수간에 서로 다른 Scale, unit
- 특히 거리 기반의 머신러닝 방법
    - standardize (표준화): 변수가 평균이 0, 표준편차가 1이 되도록 변환
    - min-max scaling: 변수 내에서 가장 큰 값1, 작은값 0

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

## Standardize

In [16]:
# 공식: (data - mean) / (std)
df.mean()

cylinders          5.471939
displacement     194.411990
horsepower       104.469388
weight          2977.584184
acceleration      15.541327
model_year        75.979592
origin             1.576531
mpg               23.445918
dtype: float64

In [17]:
df - df.mean()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,2.528061,112.58801,25.530612,526.415816,-3.541327,-5.979592,-0.576531,-5.445918
1,2.528061,155.58801,60.530612,715.415816,-4.041327,-5.979592,-0.576531,-8.445918
2,2.528061,123.58801,45.530612,458.415816,-4.541327,-5.979592,-0.576531,-5.445918
3,2.528061,109.58801,45.530612,455.415816,-3.541327,-5.979592,-0.576531,-7.445918
4,2.528061,107.58801,35.530612,471.415816,-5.041327,-5.979592,-0.576531,-6.445918
...,...,...,...,...,...,...,...,...
387,-1.471939,-54.41199,-18.469388,-187.584184,0.058673,6.020408,-0.576531,3.554082
388,-1.471939,-97.41199,-52.469388,-847.584184,9.058673,6.020408,0.423469,20.554082
389,-1.471939,-59.41199,-20.469388,-682.584184,-3.941327,6.020408,-0.576531,8.554082
390,-1.471939,-74.41199,-25.469388,-352.584184,3.058673,6.020408,-0.576531,4.554082
391,-1.471939,-75.41199,-22.469388,-257.584184,3.858673,6.020408,-0.576531,7.554082

In [18]:
df.std()

cylinders         1.705783
displacement    104.644004
horsepower       38.491160
weight          849.402560
acceleration      2.758864
model_year        3.683737
origin            0.805518
mpg               7.805007
dtype: float64

In [19]:
(df-df.mean())/df.std()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.482053,1.075915,0.663285,0.619748,-1.283618,-1.623241,-0.715726,-0.697747
1,1.482053,1.486832,1.572585,0.842258,-1.464852,-1.623241,-0.715726,-1.082115
2,1.482053,1.181033,1.182885,0.539692,-1.646086,-1.623241,-0.715726,-0.697747
3,1.482053,1.047246,1.182885,0.536160,-1.283618,-1.623241,-0.715726,-0.953992
4,1.482053,1.028134,0.923085,0.554997,-1.827320,-1.623241,-0.715726,-0.825870
...,...,...,...,...,...,...,...,...
387,-0.862911,-0.519972,-0.479835,-0.220842,0.021267,1.634321,-0.715726,0.455359
388,-0.862911,-0.930889,-1.363154,-0.997859,3.283479,1.634321,0.525711,2.633448
389,-0.862911,-0.567753,-0.531795,-0.803605,-1.428605,1.634321,-0.715726,1.095974
390,-0.862911,-0.711097,-0.661694,-0.415097,1.108671,1.634321,-0.715726,0.583482
391,-0.862911,-0.720653,-0.583754,-0.303253,1.398646,1.634321,-0.715726,0.967851

## Min-max scaling

In [20]:
df.max()

cylinders          8.0
displacement     455.0
horsepower       230.0
weight          5140.0
acceleration      24.8
model_year        82.0
origin             3.0
mpg               46.6
dtype: float64

In [21]:
df.min()

cylinders          3.0
displacement      68.0
horsepower        46.0
weight          1613.0
acceleration       8.0
model_year        70.0
origin             1.0
mpg                9.0
dtype: float64

In [22]:
(df-df.min())/(df.max()-df.min())

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.0,0.617571,0.456522,0.536150,0.238095,0.0,0.0,0.239362
1,1.0,0.728682,0.646739,0.589736,0.208333,0.0,0.0,0.159574
2,1.0,0.645995,0.565217,0.516870,0.178571,0.0,0.0,0.239362
3,1.0,0.609819,0.565217,0.516019,0.238095,0.0,0.0,0.186170
4,1.0,0.604651,0.510870,0.520556,0.148810,0.0,0.0,0.212766
...,...,...,...,...,...,...,...,...
387,0.2,0.186047,0.217391,0.333711,0.452381,1.0,0.0,0.478723
388,0.2,0.074935,0.032609,0.146583,0.988095,1.0,0.5,0.930851
389,0.2,0.173127,0.206522,0.193365,0.214286,1.0,0.0,0.611702
390,0.2,0.134367,0.179348,0.286929,0.630952,1.0,0.0,0.505319
391,0.2,0.131783,0.195652,0.313864,0.678571,1.0,0.0,0.585106

## sklearn
- 파이썬에서 표준화된 머신러닝 라이브러리
- sklearn에서 제공하는 데이터 표준화 모듈을 사용
- skearn.preprocessing
- MinMaxScaler

In [24]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/AnYeHyeon/DataScience_2023S/master/data/auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

In [30]:
# 객체생성
scaler = StandardScaler()
output = scaler.fit_transform(df) #numpy array 형태로 변환시켜서 생성
output

array([[ 1.48394702,  1.07728956,  0.66413273, ..., -1.62531533,
        -0.71664105, -0.69863841],
       [ 1.48394702,  1.48873169,  1.57459447, ..., -1.62531533,
        -0.71664105, -1.08349824],
       [ 1.48394702,  1.1825422 ,  1.18439658, ..., -1.62531533,
        -0.71664105, -0.69863841],
       ...,
       [-0.86401356, -0.56847897, -0.53247413, ...,  1.63640964,
        -0.71664105,  1.09737414],
       [-0.86401356, -0.7120053 , -0.66254009, ...,  1.63640964,
        -0.71664105,  0.5842277 ],
       [-0.86401356, -0.72157372, -0.58450051, ...,  1.63640964,
        -0.71664105,  0.96908753]])